<?php

return [
    'telemetry' => [
        'health_endpoint' => '/up',
        'dashboard_refresh_minutes' => 5,
    ],
    'alert_routes' => [
        [
            'key' => 'sev1_platform',
            'severity' => 'sev1',
            'name' => 'SEV1 platform command',
            'owner_team' => 'platform.support',
            'channels' => [
                'slack:#platform-sev1',
                'incident:on-call-primary',
            ],
            'initial_response_minutes' => 5,
            'escalation_minutes' => 15,
        ],
        [
            'key' => 'sev2_operations',
            'severity' => 'sev2',
            'name' => 'SEV2 operations response',
            'owner_team' => 'tenant.admin',
            'channels' => [
                'slack:#ops-alerts',
                'email:ops-leads@phoenixhrms.test',
            ],
            'initial_response_minutes' => 15,
            'escalation_minutes' => 60,
        ],
        [
            'key' => 'sev3_business',
            'severity' => 'sev3',
            'name' => 'SEV3 business workflow review',
            'owner_team' => 'hr.admin',
            'channels' => [
                'slack:#business-observability',
                'queue:daily-ops-review',
            ],
            'initial_response_minutes' => 60,
            'escalation_minutes' => 240,
        ],
    ],
    'services' => [
        [
            'key' => 'core_api',
            'name' => 'Core API and tenant health',
            'category' => 'platform',
            'owner_role' => 'platform.support',
            'summary' => 'The application health endpoint and centralized log pipeline form the baseline tenant-wide service availability contract.',
            'signal_keys' => [],
        ],
        [
            'key' => 'integration_delivery',
            'name' => 'Integration delivery',
            'category' => 'integrations',
            'owner_role' => 'integration.manage',
            'summary' => 'Outbound and inbound sync posture is monitored so failed deliveries and stale queues are visible before downstream drift grows.',
            'signal_keys' => [
                'integration_failed_jobs',
                'integration_stale_queue',
            ],
        ],
        [
            'key' => 'workflow_approvals',
            'name' => 'Workflow approvals',
            'category' => 'workflow',
            'owner_role' => 'workflow.monitor',
            'summary' => 'Approval-task SLA pressure is surfaced from the workflow engine so people operations and reviewers can recover stalled decisions.',
            'signal_keys' => [
                'workflow_overdue_tasks',
            ],
        ],
        [
            'key' => 'payroll_controls',
            'name' => 'Payroll controls',
            'category' => 'payroll',
            'owner_role' => 'payroll.process',
            'summary' => 'Blocked or failed payroll runs are tracked as release-critical operational issues because they directly affect pay-cycle readiness.',
            'signal_keys' => [
                'payroll_blocked_runs',
            ],
        ],
        [
            'key' => 'notification_delivery',
            'name' => 'Notification delivery',
            'category' => 'communications',
            'owner_role' => 'notification.manage',
            'summary' => 'Failed employee and operator notifications stay visible so retry handling and channel remediation are reviewable.',
            'signal_keys' => [
                'notification_failed_delivery',
            ],
        ],
        [
            'key' => 'reporting_delivery',
            'name' => 'Reporting delivery',
            'category' => 'reporting',
            'owner_role' => 'reporting.manage',
            'summary' => 'Governed report exports and subscriptions remain observable so scheduled delivery does not silently drift from certification posture.',
            'signal_keys' => [
                'report_failed_exports',
                'report_blocked_subscriptions',
            ],
        ],
        [
            'key' => 'release_governance',
            'name' => 'Release governance',
            'category' => 'release',
            'owner_role' => 'release.manage',
            'summary' => 'Protected promotion depends on the same blocking release-quality gates surfaced in the release engineering baseline.',
            'signal_keys' => [
                'release_blocking_gates',
            ],
        ],
    ],
    'signals' => [
        [
            'key' => 'integration_failed_jobs',
            'name' => 'Failed integration sync jobs',
            'service_key' => 'integration_delivery',
            'category' => 'integrations',
            'owner_role' => 'integration.manage',
            'unit' => 'jobs',
            'warning_threshold' => 1,
            'critical_threshold' => 3,
            'warning_route_key' => 'sev2_operations',
            'critical_route_key' => 'sev1_platform',
            'drill_in_label' => 'Open integration sync queue',
            'drill_in_path' => '/operations/integrations',
        ],
        [
            'key' => 'integration_stale_queue',
            'name' => 'Queued integration jobs beyond SLA',
            'service_key' => 'integration_delivery',
            'category' => 'integrations',
            'owner_role' => 'integration.manage',
            'unit' => 'jobs',
            'stale_after_minutes' => 20,
            'warning_threshold' => 1,
            'critical_threshold' => 4,
            'warning_route_key' => 'sev2_operations',
            'critical_route_key' => 'sev1_platform',
            'drill_in_label' => 'Review queued jobs',
            'drill_in_path' => '/operations/integrations',
        ],
        [
            'key' => 'workflow_overdue_tasks',
            'name' => 'Workflow tasks beyond SLA',
            'service_key' => 'workflow_approvals',
            'category' => 'workflow',
            'owner_role' => 'workflow.monitor',
            'unit' => 'tasks',
            'warning_threshold' => 1,
            'critical_threshold' => 4,
            'warning_route_key' => 'sev3_business',
            'critical_route_key' => 'sev2_operations',
            'drill_in_label' => 'Open workflow queue',
            'drill_in_path' => '/operations/lifecycle',
        ],
        [
            'key' => 'payroll_blocked_runs',
            'name' => 'Blocked or failed payroll runs',
            'service_key' => 'payroll_controls',
            'category' => 'payroll',
            'owner_role' => 'payroll.process',
            'unit' => 'runs',
            'warning_threshold' => 1,
            'critical_threshold' => 1,
            'warning_route_key' => 'sev1_platform',
            'critical_route_key' => 'sev1_platform',
            'drill_in_label' => 'Open payroll review',
            'drill_in_path' => '/payroll/review',
        ],
        [
            'key' => 'notification_failed_delivery',
            'name' => 'Failed notification deliveries',
            'service_key' => 'notification_delivery',
            'category' => 'notifications',
            'owner_role' => 'notification.manage',
            'unit' => 'deliveries',
            'warning_threshold' => 1,
            'critical_threshold' => 5,
            'warning_route_key' => 'sev3_business',
            'critical_route_key' => 'sev2_operations',
            'drill_in_label' => 'Review delivery failures',
            'drill_in_path' => '/foundation',
        ],
        [
            'key' => 'report_failed_exports',
            'name' => 'Failed report exports',
            'service_key' => 'reporting_delivery',
            'category' => 'reporting',
            'owner_role' => 'reporting.manage',
            'unit' => 'exports',
            'warning_threshold' => 1,
            'critical_threshold' => 3,
            'warning_route_key' => 'sev3_business',
            'critical_route_key' => 'sev2_operations',
            'drill_in_label' => 'Open report exports',
            'drill_in_path' => '/reporting/exports',
        ],
        [
            'key' => 'report_blocked_subscriptions',
            'name' => 'Blocked or paused report subscriptions',
            'service_key' => 'reporting_delivery',
            'category' => 'reporting',
            'owner_role' => 'reporting.manage',
            'unit' => 'subscriptions',
            'warning_threshold' => 1,
            'critical_threshold' => 2,
            'warning_route_key' => 'sev3_business',
            'critical_route_key' => 'sev2_operations',
            'drill_in_label' => 'Open report subscriptions',
            'drill_in_path' => '/reporting/subscriptions',
        ],
        [
            'key' => 'release_blocking_gates',
            'name' => 'Blocking release-quality gates',
            'service_key' => 'release_governance',
            'category' => 'release',
            'owner_role' => 'release.manage',
            'unit' => 'gates',
            'warning_threshold' => 1,
            'critical_threshold' => 1,
            'warning_route_key' => 'sev1_platform',
            'critical_route_key' => 'sev1_platform',
            'drill_in_label' => 'Open release baseline',
            'drill_in_path' => '/operations/release',
        ],
    ],
    'coverage' => [
        'workflows' => [
            [
                'key' => 'leave_approval_workflow',
                'name' => 'Leave approval workflow',
                'workflow_key' => 'leave-approval',
                'owner_role' => 'workflow.monitor',
                'signal_keys' => ['workflow_overdue_tasks'],
                'summary' => 'Manager and HR leave approvals inherit workflow-task SLA monitoring so stalled decisions are visible before employee balances drift.',
            ],
            [
                'key' => 'attendance_correction_workflow',
                'name' => 'Attendance correction workflow',
                'workflow_key' => 'attendance-correction-approval',
                'owner_role' => 'workflow.monitor',
                'signal_keys' => ['workflow_overdue_tasks'],
                'summary' => 'Attendance corrections stay within the observability baseline so unresolved manager or HR approvals cannot disappear between shifts.',
            ],
            [
                'key' => 'offboarding_clearance_workflow',
                'name' => 'Employee offboarding clearance workflow',
                'workflow_key' => 'employee-offboarding-clearance',
                'owner_role' => 'workflow.monitor',
                'signal_keys' => ['workflow_overdue_tasks'],
                'summary' => 'Exit clearances are tracked as release-critical workflow coverage because blocked offboarding can hold asset and compliance closure open.',
            ],
        ],
        'integrations' => [
            [
                'key' => 'identity_directory_sync',
                'name' => 'Identity directory sync',
                'system_key' => 'identity_directory',
                'event_keys' => [
                    'employee.created',
                    'employee.updated',
                    'directory.profile.sync',
                ],
                'stale_after_minutes' => 20,
                'owner_role' => 'integration.manage',
                'signal_keys' => [
                    'integration_failed_jobs',
                    'integration_stale_queue',
                ],
                'summary' => 'Provisioning and inbound profile synchronization remain monitored across approved directory events and active webhook subscriptions.',
            ],
            [
                'key' => 'payroll_partner_delivery',
                'name' => 'Payroll partner delivery',
                'system_key' => 'payroll_partner',
                'event_keys' => [
                    'attendance.record.updated',
                    'leave.request.approved',
                    'payroll.payslip.generated',
                ],
                'stale_after_minutes' => 20,
                'owner_role' => 'integration.manage',
                'signal_keys' => [
                    'integration_failed_jobs',
                    'integration_stale_queue',
                ],
                'summary' => 'Payroll-critical downstream updates remain under monitoring so attendance, leave, and payslip events stay reviewable before pay-cycle cutover.',
            ],
        ],
        'release_critical' => [
            [
                'key' => 'release_quality_gates',
                'name' => 'Release quality gates',
                'kind' => 'gates',
                'owner_role' => 'release.manage',
                'signal_keys' => ['release_blocking_gates'],
                'summary' => 'Blocking CI, dependency-security, and contract gates are part of the same operational telemetry contract as live runtime signals.',
            ],
            [
                'key' => 'protected_promotion_lanes',
                'name' => 'Protected promotion lanes',
                'kind' => 'environments',
                'owner_role' => 'release.manage',
                'signal_keys' => ['release_blocking_gates'],
                'summary' => 'Protected pull-request, staging, and production promotion lanes remain monitored so launch blockers are visible before go-live review.',
            ],
        ],
    ],
];
