<?php

return [
    'countries' => [
        'IN' => [
            'label' => 'India',
            'locale' => 'en-IN',
            'language' => 'en',
            'timezone' => 'Asia/Kolkata',
            'currency' => 'INR',
            'time_format' => '24h',
            'week_start' => 'monday',
            'launch_default' => true,
            'expansion_placeholder' => true,
        ],
        'US' => [
            'label' => 'United States',
            'locale' => 'en-US',
            'language' => 'en',
            'timezone' => 'America/New_York',
            'currency' => 'USD',
            'time_format' => '12h',
            'week_start' => 'sunday',
            'launch_default' => false,
            'expansion_placeholder' => true,
        ],
        'GB' => [
            'label' => 'United Kingdom',
            'locale' => 'en-GB',
            'language' => 'en',
            'timezone' => 'Europe/London',
            'currency' => 'GBP',
            'time_format' => '24h',
            'week_start' => 'monday',
            'launch_default' => false,
            'expansion_placeholder' => true,
        ],
        'DE' => [
            'label' => 'Germany',
            'locale' => 'de-DE',
            'language' => 'de',
            'timezone' => 'Europe/Berlin',
            'currency' => 'EUR',
            'time_format' => '24h',
            'week_start' => 'monday',
            'launch_default' => false,
            'expansion_placeholder' => true,
        ],
        'AE' => [
            'label' => 'United Arab Emirates',
            'locale' => 'en-AE',
            'language' => 'en',
            'timezone' => 'Asia/Dubai',
            'currency' => 'AED',
            'time_format' => '12h',
            'week_start' => 'monday',
            'launch_default' => false,
            'expansion_placeholder' => true,
        ],
        'SG' => [
            'label' => 'Singapore',
            'locale' => 'en-SG',
            'language' => 'en',
            'timezone' => 'Asia/Singapore',
            'currency' => 'SGD',
            'time_format' => '24h',
            'week_start' => 'monday',
            'launch_default' => false,
            'expansion_placeholder' => true,
        ],
    ],
    'time_formats' => [
        ['code' => '12h', 'label' => '12-hour'],
        ['code' => '24h', 'label' => '24-hour'],
    ],
    'fallback' => [
        'country_code' => 'IN',
        'locale' => 'en-IN',
        'language' => 'en',
        'timezone' => 'Asia/Kolkata',
        'currency' => 'INR',
        'time_format' => '24h',
        'week_start' => 'monday',
    ],
];
