<?php

return [
    'policy' => [
        'protected_branch' => 'main',
        'promotion_rule' => 'Any blocking gate that is failing, pending, or missing current evidence blocks protected-environment promotion until an authorized operator reviews the run.',
        'required_workflow_names' => [
            'Release Quality Gates',
            'API CI',
            'Web CI',
        ],
        'reviewer_roles' => [
            'platform.super_admin',
            'platform.support',
            'tenant.admin',
            'it.admin',
        ],
        'artifact_paths' => [
            '.github/workflows/release-quality-gates.yml',
            '.github/workflows/api-ci.yml',
            '.github/workflows/web-ci.yml',
            'apps/api/openapi/README.md',
        ],
    ],
    'gates' => [
        [
            'key' => 'api_quality',
            'name' => 'API quality gate',
            'category' => 'backend',
            'status' => 'passing',
            'blocking' => true,
            'owner_role' => 'platform.support',
            'workflow_name' => 'API CI',
            'workflow_path' => '.github/workflows/api-ci.yml',
            'summary' => 'Protects the Laravel API surface with manifest validation, style checks, static analysis, automated tests, dependency audit, and OpenAPI linting.',
            'last_run_at' => '2026-07-01T09:10:00+05:30',
            'required_for' => ['pull_request', 'staging', 'production'],
            'artifact_refs' => [
                'apps/api/composer.json',
                'apps/api/scripts/openapi-lint.sh',
                'apps/api/openapi/README.md',
            ],
            'checks' => [
                [
                    'key' => 'composer_validate',
                    'label' => 'Composer manifest validation',
                    'status' => 'passing',
                    'command' => 'composer validate --strict',
                ],
                [
                    'key' => 'code_style',
                    'label' => 'Laravel Pint code style',
                    'status' => 'passing',
                    'command' => 'composer lint',
                ],
                [
                    'key' => 'static_analysis',
                    'label' => 'Larastan and PHPStan',
                    'status' => 'passing',
                    'command' => 'composer analyse',
                ],
                [
                    'key' => 'backend_tests',
                    'label' => 'Backend regression suite',
                    'status' => 'passing',
                    'command' => 'php artisan test',
                ],
            ],
        ],
        [
            'key' => 'web_quality',
            'name' => 'Web quality gate',
            'category' => 'frontend',
            'status' => 'passing',
            'blocking' => true,
            'owner_role' => 'it.admin',
            'workflow_name' => 'Web CI',
            'workflow_path' => '.github/workflows/web-ci.yml',
            'summary' => 'Protects the website workspace with type safety, linting, route tests, page tests, and production build validation.',
            'last_run_at' => '2026-07-01T09:14:00+05:30',
            'required_for' => ['pull_request', 'staging', 'production'],
            'artifact_refs' => [
                'apps/web/package.json',
                'apps/web/src/app/routes/AppRoutes.test.tsx',
            ],
            'checks' => [
                [
                    'key' => 'typecheck',
                    'label' => 'TypeScript typecheck',
                    'status' => 'passing',
                    'command' => 'npm run typecheck',
                ],
                [
                    'key' => 'lint',
                    'label' => 'ESLint',
                    'status' => 'passing',
                    'command' => 'npm run lint',
                ],
                [
                    'key' => 'tests',
                    'label' => 'Vitest suite',
                    'status' => 'passing',
                    'command' => 'npm run test:run',
                ],
                [
                    'key' => 'build',
                    'label' => 'Production build',
                    'status' => 'passing',
                    'command' => 'npm run build',
                ],
            ],
        ],
        [
            'key' => 'dependency_security',
            'name' => 'Dependency security gate',
            'category' => 'security',
            'status' => 'passing',
            'blocking' => true,
            'owner_role' => 'platform.support',
            'workflow_name' => 'Release Quality Gates',
            'workflow_path' => '.github/workflows/release-quality-gates.yml',
            'summary' => 'Runs dependency audits for PHP and JavaScript toolchains before any protected promotion can proceed.',
            'last_run_at' => '2026-07-01T09:18:00+05:30',
            'required_for' => ['pull_request', 'staging', 'production'],
            'artifact_refs' => [
                'apps/api/composer.lock',
                'apps/api/package-lock.json',
                'apps/web/package-lock.json',
            ],
            'checks' => [
                [
                    'key' => 'composer_audit',
                    'label' => 'Composer audit',
                    'status' => 'passing',
                    'command' => 'composer audit --locked',
                ],
                [
                    'key' => 'api_npm_audit',
                    'label' => 'API toolchain npm audit',
                    'status' => 'passing',
                    'command' => 'npm audit --audit-level=high',
                ],
                [
                    'key' => 'web_npm_audit',
                    'label' => 'Web runtime npm audit',
                    'status' => 'passing',
                    'command' => 'npm audit --omit=dev --audit-level=high',
                ],
            ],
        ],
        [
            'key' => 'contract_validation',
            'name' => 'Contract validation gate',
            'category' => 'governance',
            'status' => 'passing',
            'blocking' => true,
            'owner_role' => 'tenant.admin',
            'workflow_name' => 'API CI',
            'workflow_path' => '.github/workflows/api-ci.yml',
            'summary' => 'Validates the governed OpenAPI inventory so downstream web, QA, and integration consumers are blocked from drifting contracts.',
            'last_run_at' => '2026-07-01T09:21:00+05:30',
            'required_for' => ['pull_request', 'staging', 'production'],
            'artifact_refs' => [
                'apps/api/openapi/README.md',
                'apps/api/openapi/sprint-09-integrations.yaml',
                'apps/api/openapi/sprint-09-mobile-ess-globalization.yaml',
            ],
            'checks' => [
                [
                    'key' => 'openapi_inventory',
                    'label' => 'OpenAPI inventory maintained',
                    'status' => 'passing',
                    'command' => 'apps/api/openapi/README.md reviewed in pull requests',
                ],
                [
                    'key' => 'openapi_lint',
                    'label' => 'OpenAPI lint',
                    'status' => 'passing',
                    'command' => 'npm run openapi:lint',
                ],
            ],
        ],
    ],
    'environments' => [
        [
            'key' => 'pull_request',
            'name' => 'Pull request merge gate',
            'manual_approval_required' => false,
            'required_gate_keys' => [
                'api_quality',
                'web_quality',
                'dependency_security',
                'contract_validation',
            ],
        ],
        [
            'key' => 'staging',
            'name' => 'Staging promotion',
            'manual_approval_required' => false,
            'required_gate_keys' => [
                'api_quality',
                'web_quality',
                'dependency_security',
                'contract_validation',
            ],
        ],
        [
            'key' => 'production',
            'name' => 'Production promotion',
            'manual_approval_required' => true,
            'manual_approval_label' => 'Authorized release approval is still required after automated gates pass.',
            'required_gate_keys' => [
                'api_quality',
                'web_quality',
                'dependency_security',
                'contract_validation',
            ],
        ],
    ],
];
