<?php

return [
    'policy' => [
        'primary_region' => 'ap-south-1',
        'secondary_region' => 'ap-southeast-1',
        'backup_cadence' => 'Continuous database WAL shipping with nightly application snapshots at 02:00 Asia/Kolkata.',
        'restore_validation_cadence' => 'Critical restore paths are validated weekly or monthly according to scenario cadence.',
        'dr_drill_cadence' => 'Regional failover drills are required at least once per quarter.',
        'retention_policy' => 'Daily backups retained for 35 days, weekly checkpoints for 12 weeks, and monthly archives for 13 months.',
        'encryption_posture' => 'Backup artifacts are encrypted at rest with tenant-approved KMS keys and in transit over private transport.',
        'coverage_scope' => 'Application data, payroll artifacts, document storage metadata, and release-critical configuration baselines.',
        'default_rpo_minutes' => 60,
        'default_rto_minutes' => 240,
        'artifact_refs' => [
            '.github/workflows/release-quality-gates.yml',
            'docs/runbooks/backup-restore-disaster-recovery-validation.md',
            'docs/files/40-production-operations-runbook.md',
        ],
    ],
    'scenarios' => [
        'daily_application_backup' => [
            'name' => 'Daily application backup',
            'scenario_type' => 'backup',
            'environment' => 'production',
            'owner_role' => 'platform.support',
            'cadence_days' => 1,
            'recovery_point_objective_minutes' => 60,
            'recovery_time_objective_minutes' => 240,
            'summary' => 'Confirms production application and database backup jobs complete successfully with encrypted artifact evidence.',
            'evidence_requirements' => [
                'Backup job identifier or snapshot reference',
                'Retention and checksum confirmation',
                'Operator sign-off in the recovery log',
            ],
        ],
        'monthly_database_restore' => [
            'name' => 'Monthly database restore validation',
            'scenario_type' => 'restore',
            'environment' => 'staging',
            'owner_role' => 'tenant.admin',
            'cadence_days' => 30,
            'recovery_point_objective_minutes' => 60,
            'recovery_time_objective_minutes' => 180,
            'summary' => 'Restores the governed production backup into staging and verifies authentication, employee directory, and reporting read paths.',
            'evidence_requirements' => [
                'Restore execution log',
                'Schema and row-count validation output',
                'Smoke-test evidence for auth and employee search',
            ],
        ],
        'payroll_artifact_restore' => [
            'name' => 'Payroll artifact restore rehearsal',
            'scenario_type' => 'restore',
            'environment' => 'staging',
            'owner_role' => 'it.admin',
            'cadence_days' => 14,
            'recovery_point_objective_minutes' => 30,
            'recovery_time_objective_minutes' => 120,
            'summary' => 'Verifies protected payslip and payroll-export artifacts can be restored with intact metadata, access controls, and audit visibility.',
            'evidence_requirements' => [
                'Restored artifact reference',
                'Access-control verification notes',
                'Payroll owner acknowledgement',
            ],
        ],
        'regional_failover_drill' => [
            'name' => 'Regional failover drill',
            'scenario_type' => 'disaster_recovery',
            'environment' => 'secondary_region',
            'owner_role' => 'platform.super_admin',
            'cadence_days' => 90,
            'recovery_point_objective_minutes' => 15,
            'recovery_time_objective_minutes' => 120,
            'summary' => 'Exercises failover sequencing, role handoffs, and launch-critical smoke checks before approving regional recovery readiness.',
            'evidence_requirements' => [
                'Incident timeline and command log',
                'Failover and failback checkpoint evidence',
                'Launch-critical workflow verification results',
            ],
        ],
    ],
    'runbook' => [
        [
            'key' => 'declare',
            'name' => 'Declare recovery scenario and assign incident command',
            'sequence' => 1,
            'owner_role' => 'platform.super_admin',
            'objective' => 'Identify the scenario, assign accountable leads, and freeze unsafe changes before recovery actions begin.',
            'evidence_requirements' => [
                'Scenario declaration timestamp',
                'Incident commander and communications owner',
            ],
        ],
        [
            'key' => 'stabilize',
            'name' => 'Stabilize writes and confirm backup set',
            'sequence' => 2,
            'owner_role' => 'platform.support',
            'objective' => 'Protect data integrity by stopping risky writes and confirming the recovery source is complete and encrypted.',
            'evidence_requirements' => [
                'Protected-write freeze confirmation',
                'Backup identifier and checksum proof',
            ],
        ],
        [
            'key' => 'execute',
            'name' => 'Execute restore or failover sequence',
            'sequence' => 3,
            'owner_role' => 'it.admin',
            'objective' => 'Restore the governed dataset or shift runtime to the approved secondary environment using the validated sequence.',
            'evidence_requirements' => [
                'Execution log with timestamps',
                'Recovered environment reference',
            ],
        ],
        [
            'key' => 'validate',
            'name' => 'Validate launch-critical workflows',
            'sequence' => 4,
            'owner_role' => 'tenant.admin',
            'objective' => 'Verify sign-in, employee search, payroll evidence, and release-critical monitoring before declaring readiness.',
            'evidence_requirements' => [
                'Smoke-test checklist output',
                'Monitoring and alert baseline confirmation',
            ],
        ],
        [
            'key' => 'close',
            'name' => 'Capture evidence, decisions, and follow-up actions',
            'sequence' => 5,
            'owner_role' => 'tenant.admin',
            'objective' => 'Record the recovery outcome, residual risk, and remediation owners so readiness remains reviewable.',
            'evidence_requirements' => [
                'Linked evidence artifacts',
                'Outcome summary and remediation owners',
            ],
        ],
    ],
];
